services:
  ev_registry:
      build:
        context: .  # Ajusta a la ruta donde esté el Dockerfile de Registry
        dockerfile: dockerfile
      container_name: ev_registry
      environment:
        # Conexión a la BD compartida (Mismos valores que api_central y ev_central)
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USER: usuario
        DB_PASSWORD: contraseña
        DB_NAME: database
        
        # Configuración propia del Registry
        REGISTRY_PORT: 9000
        API_CENTRAL_BASE: ${API_CENTRAL_BASE} # Para notificar a Central vía API REST
      ports:
        - "9000:9000"
      volumes:
        - ./logs:/app/logs
        - ../certs:/app/certs:ro
      tty: true
      stdin_open: true