services:

  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: 'ZGI1NTk0YmY3NzVjNDk5MDY' #Me lo he inventado, el id es arbitrario
      KAFKA_NODE_ID: 1 #Solo hay un nodo en el cluster

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 #Un controlador
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #Una copia de los metadatos del kafka porque tenemos un nodo en el cluster

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.38:9092 #PLAINTEXT_HOST://192.168.56.1:9092 #Hay que poner la IP del que lanza el docker en vez de kafka
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs 

    volumes:
      - kafka_kraft:/var/lib/kafka/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  ev_central:
    build:
      context: ./central
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: usuario
      DB_PASSWORD: contraseña
      DB_NAME: database
    ports:
      - "5000:5000"
    restart: unless-stopped

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    restart: unless-stopped

volumes:
  kafka_kraft: