CREATE TABLE ChargingPoint (
    ID           VARCHAR(20) PRIMARY KEY,
    Ubicacion    VARCHAR(100),
    PRECIO       DECIMAL(6,2),
    ESTADO       ENUM('ACTIVADO','PARADO','SUMINISTRANDO','DESCONECTADO','AVERIADO','AUTORIZADO') NOT NULL,
    CONDUCTOR_ID VARCHAR(20),
    CONSUMO_KW   DECIMAL(6,2),
    IMPORTE_EU   DECIMAL(6,2),
    ALERTA_METEO TINYINT(1) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS WeatherAlert (
    location VARCHAR(100) PRIMARY KEY,
    alert_active TINYINT(1) NOT NULL DEFAULT 0,
    last_temp DECIMAL(6,2) NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPRegistry (
    cp_id VARCHAR(50) PRIMARY KEY,
    ubicacion VARCHAR(100) NOT NULL,
    token VARCHAR(64) NOT NULL,
    registrado TINYINT(1) DEFAULT 1,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPAuthentication (
    cp_id VARCHAR(50) PRIMARY KEY,
    encryption_key VARCHAR(64) NOT NULL,
    authenticated TINYINT(1) DEFAULT 1,
    fecha_auth TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cp_id) REFERENCES CPRegistry(cp_id)
);
