CREATE TABLE ChargingPoint (
    ID           VARCHAR(20) PRIMARY KEY,
    Ubicacion    VARCHAR(100),
    PRECIO       DECIMAL(6,2),
    ESTADO       ENUM('ACTIVADO','PARADO','SUMINISTRANDO','DESCONECTADO','AVERIADO','AUTORIZADO') NOT NULL,
    CONDUCTOR_ID VARCHAR(20),
    CONSUMO_KW   DECIMAL(6,2),
    IMPORTE_EU   DECIMAL(6,2),
    ALERTA_METEO TINYINT(1) NOT NULL DEFAULT 0
);
