FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY EV_CP_M.py .

# Por ahora dejamos los argumentos fijos
CMD ["sh", "-c", "python -u EV_CP_M.py $ENGINE_IP $ENGINE_PORT $CENTRAL_IP $CENTRAL_PORT $CP_ID"]
