services:
  engine:
    build:
      context: ../engine
      dockerfile: Dockerfile
    container_name: engine
    ports:
      - "6000:6000"       # Exponemos el puerto por si quieres probar desde fuera
    environment:
      KAFKA_BROKER: 192.168.1.33:9092

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor
    depends_on:
      engine:
        condition: service_started
    environment:
      ENGINE_IP: engine
      ENGINE_PORT: 6000
      CENTRAL_IP: 192.168.1.33
      CENTRAL_PORT: 5000
      CP_ID: CP001
