FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY EV_Driver.py .

# Por defecto, toma broker e id de variables de entorno
CMD ["sh", "-c", "python -u EV_Driver.py ${KAFKA_BROKER} ${DRIVER_ID}"]