services:
  driver1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver1
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV001
    volumes:
      - ./data:/app/data
  driver2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver2
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV002
    volumes:
      - ./data:/app/data

  driver3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver3
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV003
    volumes:
      - ./data:/app/data

  driver4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver4
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV004
    volumes:
      - ./data:/app/data

  driver5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver5
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV005
    volumes:
      - ./data:/app/data

  driver6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver6
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV006
    volumes:
      - ./data:/app/data

  driver7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver7
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV007
    volumes:
      - ./data:/app/data

  driver8:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver8
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV008
    volumes:
      - ./data:/app/data

  driver9:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver9
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV009
    volumes:
      - ./data:/app/data

  driver10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver10
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: ${KAFKA_BROKER}
      # Identidad del conductor/cliente
      DRIVER_ID: DRV0010
    volumes:
      - ./data:/app/data


