services:
  driver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver-DRV001
    environment:
      # Kafka externo (listener EXTERNAL)
      KAFKA_BROKER: 192.168.1.33:9092
      # Identidad del conductor/cliente
      DRIVER_ID: DRV001