FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY EV_Central.py .

CMD ["python","-u","EV_Central.py", "5000", "192.168.1.35", "9092"]
