services:
  api_central:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      REST_PORT: 8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: usuario
      DB_PASSWORD: contraseña
      DB_NAME: database
      API_CERT: /app/certs/certificado_api_central.crt
      API_KEY: /app/certs/clave_privada_api_central.pem
    command: ["python", "-u", "API_Central.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ../certs:/app/certs:ro

  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: 'ZGI1NTk0YmY3NzVjNDk5MDY' #Me lo he inventado, el id es arbitrario
      KAFKA_NODE_ID: 1 #Solo hay un nodo en el cluster

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 #Un controlador
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #Una copia de los metadatos del kafka porque tenemos un nodo en el cluster

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.18.18:9092 #PLAINTEXT_HOST://192.168.18.28:9092 #Hay que poner la IP del que lanza el docker en vez de kafka
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs 

    volumes:
      - kafka_kraft:/var/lib/kafka/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3307:3306"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
  ev_w:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      api_central:
        condition: service_started
    environment:
      OPENWEATHER_API_KEY: "c469d40985c2772a191a871b666b842d"
      API_CENTRAL_BASE: "https://api_central:8000"
      POLL_INTERVAL: 4
      CA_CERT: /app/certs/certificado_CA.crt
    command: ["python", "-u", "EV_W.py"]
    tty: true
    stdin_open: true
    volumes:
      - ./logs:/app/logs
      - ../certs:/app/certs:ro


  ev_central:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CENTRAL_PORT: 5000        # puerto donde escucha tu socket
      KAFKA_IP: 192.168.18.18 # IP LAN del host donde corre Kafka
      KAFKA_PORT: 9092
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: usuario
      DB_PASSWORD: contraseña
      DB_NAME: database
      TLS_ENABLED: "1"
      TLS_CERT: /app/certs/certServ.pem
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    volumes:
      - ./logs:/app/logs
      - ../certs:/app/certs:ro

  ev_front:
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      FRONT_PORT: 8080
      API_CENTRAL_BASE: https://api_central:8000
    ports:
      - "8080:8080"
    depends_on:
      - api_central
volumes:
  kafka_kraft: